### ISSUE TITLE
Can't use Meteor.userId() inside route?

### ISSUE THREAD

**Issue by Sewdn** [meteorhacks/picker#10]
Hi,

I can't seem to use Meteor.userId() inside a server side route of Picker.
At least, I can in one app, but in a brand new app without any other dependencies it seems I can't.
The error i get:
Meteor.userId can only be invoked in method calls. Use this.userId in publish functions

I thought Picker ran every route inside a Fiber, and Meteor.userId() should be available, no?

**Comment by Sewdn** [comment]
As soon as I add fast-render, but only then, I can access Meteor.userId() from within a Picker route (and probably any connectHandler)...

**Comment by dandv** [comment]
:+1:

**Comment by arunoda** [comment]
Meteor.userId() needs some special handling and needs to send the loginToken as a cookie. FastRender does it.

I think this is not something needs to be baked into picker. We may can abstract it away from fast-render.

**Comment by titovanton** [comment]
i see at least 2 issues with problem to get user inside callback. Why don't  you think it is important and needless?

**Comment by mhagmajer** [comment]
You might consider https://github.com/mhagmajer/server-router for server routing with authentication.
