### ISSUE TITLE
How to get post data?

### ISSUE THREAD

**Issue by benjick** [meteorhacks/picker#11]
Hi

Trying to break away from iron:router but I'm struggling with some basic concepts.

I'm trying to recieve POST-data from Mailgun (incoming mail), this is my code:

```js
var bodyParser = Meteor.npmRequire('body-parser'); 
Picker.middleware(bodyParser.urlencoded({ extended: false }));
Picker.middleware(bodyParser.json());

var post = Picker.filter(function(req, res) {
  return req.method == "POST";
});

post.route('/post', function(params, req, res, next) {
  console.log(params);   // { query: {} }
  console.log(req.data); // undefined
  console.log(req.body); // {}
  res.end();
});
```

How can I solve this?

If I make a HTTP.post on my own with `data` instead of `params` it works, but I can't control what Mailgun sends me

**Comment by c316** [comment]
@benjick Did you figure this out? I'm wondering the same thing.

**Comment by Streemo** [comment]
My old solution stopped working... I've been doing `req.on('data', callback)`, but the callback is never called.

**Comment by benjick** [comment]
@c316 @Streemo Yeah

I did it like this: https://github.com/benjick/meteor-telegram-bot/blob/6dd5c220e68eaf477a96997779acff4cc3631c89/routes.js

Not that this is a package, so I could do this in the package.js: https://github.com/benjick/meteor-telegram-bot/blob/6dd5c220e68eaf477a96997779acff4cc3631c89/package.js#L12
