### ISSUE TITLE
how to get IP of the client?

### ISSUE THREAD

**Issue by Alino** [meteorhacks/picker#13]
I need to get the IP of the client who requests the route. In iron router I did it like this:

```coffeescript
Router.map ->
  @route 'importXML',
    where: 'server'
    path: '/importXML'
    action: ->
      clientIP = @request.connection.remoteAddress
      if clientIP is '127.0.0.1'
        @response.end 'executed from local host'
        Meteor.call('importAllXMLs')
      else
        @response.end 'error: access denied'
```
Wished result - only server can make http request to itself to execute some code.
Can this be achieved with picker?

**Comment by arunoda** [comment]
Of course yes. In picker response object is the standard NodeJS response object. You can do it.

**Comment by Alino** [comment]
oh, thank you :)
