### ISSUE TITLE
How are we supposed to get the content of the request?

### ISSUE THREAD

**Issue by Lepozepo** [meteorhacks/picker#16]
Hi @arunoda , how are we supposed to get the content in the request? I'm trying to use the package to pick up information from a webhook.

**Comment by Streemo** [comment]
I'm doing the exact same thing right now. You have to listen to the data event, and then manually string together the chunks. Once that's finished, you can listen to the end event and perform your actions on the data.

```
var data = '';
req.on('data', function(chunk){
  if (chunk) {
    data += chunk
  }
})

req.on('end', function(error){
  data = JSON.parse(data);
  doSomethingWithData(data);
})
```

**Comment by Streemo** [comment]
Hey @Lepozepo 

If you want a different way to do it, I had to get it synchronously because in the `'end'` of the response callback, it is not running in a Fiber, according to the Meteor  output.

So you can do whatI did here if want to get data from the request.

https://github.com/meteorhacks/picker/issues/17

```
var yourData = Picker.getPostDataSync(request);
```

**Comment by Lepozepo** [comment]
Thank you! I ended up using restivus instead until arunoda releases v3 or a new version of picker :)



Marcelo Reyna

**Comment by arunoda** [comment]
Hey, you can any of the nodejs express and connect middleware with picker. So you can use any of them for the body parsing. See: https://github.com/expressjs/body-parser

Restivis also a good solution.

However flow-router 3.0 does not comes with server side routing. It's server side rendering.

**Comment by Lepozepo** [comment]
Sweet, then I guess I'll be sticking to restivus for my app, it just makes it a bit easier to manage but hopefully that simplicity won't come at a cost down the road. Thank you both @Streemo and @arunoda
