### ISSUE TITLE
How to get userId from picker route?

### ISSUE THREAD

**Issue by lsunsi** [meteorhacks/picker#18]
This seems a pretty common thing in Meteor, is there a way to get this info from server-side?
Tried Meteor.userId() and this.userId, both without luck

Am I doing something wrong?

**Comment by arunoda** [comment]
You can get a Meteor.user() from a method or publication which is behind DDP. Picker is not build for that purpose. You may need to use some other solution.

**Comment by neopostmodern** [comment]
Could you please add this to the README? It might be obvious to some, but it could save some time for others...

**Comment by mhagmajer** [comment]
You may check out https://github.com/mhagmajer/server-router for server routing with authentication.
