### ISSUE TITLE
Update README to swap deprecated bodyParser() call

### ISSUE THREAD

**Issue by themeteorchef** [meteorhacks/picker#19]
Howdy!

It looks like the example under [Middlewares](https://github.com/meteorhacks/picker#middlewares) in the docs needs an update. When you run this now, bodyParser throws a deprecation warning saying that calling it directly is no longer supported. Instead, it looks like you need to do:

![bodyParser deprecation warning](http://cl.ly/image/0c0f2f3u3i3K/Image%202015-08-20%20at%2011.02.59%20AM.png)
```javascript
var bodyParser = Meteor.npmRequire('body-parser');
  
Picker.middleware( bodyParser.json() );
Picker.middleware( bodyParser.urlencoded( { extended: false } ) );
```

This works as expected for handling the body and negates the deprecation warning.

**Comment by arunoda** [comment]
Okay. Why don't you send me a PR ? :)

**Comment by themeteorchef** [comment]
I knew you were going to say that :p 

I'll whip something up.

**Comment by arunoda** [comment]
Merged! :)
