### ISSUE TITLE
Picker.filter function runs ~80 times for a single request?

### ISSUE THREAD

**Issue by Streemo** [meteorhacks/picker#23]
I'm working on localhost, using chrome.

This is a very simple example:

```
var Router = Picker.filter(function(req, res){
	console.log('ssred')
	return /_escaped_fragment_/.test(req.url)
})

Router.route('/', function(params,req,res,next){
	console.log('hello')
})
```

If I go to localhost:port (without escaped fragment) I see in my meteor log "ssred" printed approximately 80 times. If I use curl, it is only printed once. If I go to the escaped fragment url, "hello" is printed once.

I am curious what might be causing this. Is this due to Meteor's sock.js setup? Have you experienced the issue @arunoda ?

**Comment by arunoda** [comment]
It's not an issue. In your filter, it sees all the http requests coming to
your app.

In typical meteor app there are other http requests like css, js. That's
why there are 80. This is specially in Dev.

When you curling it, it's just one.

**Comment by Streemo** [comment]
Ah silly me! Thanks @arunoda that makes more sense.
