### ISSUE TITLE
Support prefixed paths

### ISSUE THREAD

**Issue by mquandalle** [meteorhacks/picker#26]
Since Picker explicitly targets Meteor, it should handle the prefixed path exposed via the `ROOT_URL` environment variable.

See https://github.com/kadirahq/flow-router/issues/315 for the related issue on flow-router.

**Comment by mquandalle** [comment]
Did you close this on purpose @arunoda?

**Comment by arunoda** [comment]
Nope. Picker in unopiniated server side router. We can't handle it here.

**Comment by arunoda** [comment]
Forgot to send the message. You can see it on the top.
