### ISSUE TITLE
Is it possible to redirect?

### ISSUE THREAD

**Issue by AdamBrodzinski** [meteorhacks/picker#27]
I can't find any info the guides or issues... is there a way to redirect inside of the route? I tried using `req.redirect('/foo')` but redirect was undefined.

**Comment by arunoda** [comment]
This is a low level router. So, you need to do this.

```
res.writeHead(301, {Location: "/foo"});
res.end();
```

**Comment by AdamBrodzinski** [comment]
Ah! Thanks!! Hey you're the best @arunoda !! :beers:
