### ISSUE TITLE
Picker + Fast-Render = Empty req.body

### ISSUE THREAD

**Issue by voidale** [meteorhacks/picker#30]
Well I just noticed my `req.body` comes empty after I added fast-render it's a server-side POST only route.

**Comment by arunoda** [comment]
Hmm. I'd like to have a sample repo or code where I can reproduce this.

**Comment by voidale** [comment]
@arunoda ok, I will get meteorpad just a moment, hopefully this is not unique to my app.

**Comment by arunoda** [comment]
Cool.

**Comment by voidale** [comment]
@arunoda not sure if this meteorpad related but I don't have `req.body` on this meteorpad http://meteorpad.com/pad/zR52jKAGhviGituE6/Leaderboard but it has the code usually this code works and after adding fast-render `req.body` is empty object `{}` in meteorpad it's undefined dunno why I guess need to test this locally

**Comment by arunoda** [comment]
Meteor pad is sometimes buggy. Put it to a GH repo and send it to me.

**Comment by voidale** [comment]
ok sorry it's false alarm! It seems to work on clean project. I probably have a different conflict I will post here if I find what kind of package causes it. It's working without fast-render on my project when adding it. It stops so I don't know how it's actually all connected to it.
