### ISSUE TITLE
Is it possible to not render all of the http content on server side route?

### ISSUE THREAD

**Issue by c316** [meteorhacks/picker#31]
I'm using this as an API endpoint. I receive a webhook and I don't need to render my whole app just to tell the server that everything is "ok". 

Should I look for another package (any suggestions) or is this the right package for this? 

Thanks

**Comment by arunoda** [comment]
Yeah. This is what you should look at.

**Comment by c316** [comment]
Ok, thanks. I've already got a Picker route in place, but I can see that Picker responds with much more than what I need for a simple POST endpoint. It appears to be trying to render the whole app.

**Comment by c316** [comment]
Thanks, I found it in the docs. 

Looks like I just needed to add this  -> ```return req.method == "POST";``` after my ```res.end();```
