### ISSUE TITLE
Disable fast-render inject-data

### ISSUE THREAD

**Issue by delgermurun** [meteorhacks/picker#6]
How can I disable fast-render?

There is a fast-render's `script` tag inside incoming html. But I think it's not necessarily, since all data rendered on server.

**Comment by arunoda** [comment]
We need to implement this as a fastRender. Right now, it only detect html
using the DOCTYPE. We need to do change it in a way to detect for something
meteor specific, not just all HTML docs.

So, this should go into fast-render repo.

**Comment by delgermurun** [comment]
https://github.com/meteorhacks/fast-render/issues/108
